String API_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxYWFzbXFkdWx0YmNpbXp5cGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc5NzA4MzYsImV4cCI6MjAzMzU0NjgzNn0.DqW1tyfdETFYJVl-BjRqnFvDlBd-862LjeubmnWvBrE";
String API_URL = "https://tqaasmqdultbcimzypds.supabase.co";
